# Generated by Django 6.0.1 on 2026-02-04 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_message_school_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schoolclass', verbose_name='Выберите класс (Если оставить пустым, сообщение будет для всех)'),
        ),
    ]
